import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'pa' | 'ml';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive translation dictionaries
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.attendance': 'Attendance',
    'nav.classes': 'Classes',
    'nav.students': 'Students',
    'nav.faculty': 'Faculty',
    'nav.reports': 'Reports',
    'nav.analytics': 'Analytics',
    'nav.settings': 'Settings',
    'nav.logout': 'Sign Out',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.overall_attendance': 'Overall Attendance',
    'dashboard.total_students': 'Total Students',
    'dashboard.active_classes': 'Active Classes',
    'dashboard.at_risk_students': 'At Risk Students',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.start_class': 'Start Class Session',
    'dashboard.face_recognition': 'Face Recognition',
    'dashboard.generate_report': 'Generate Report',
    'dashboard.view_analytics': 'View Analytics',
    
    // Attendance
    'attendance.title': 'Attendance Management',
    'attendance.my_attendance': 'My Attendance',
    'attendance.mark_attendance': 'Mark your attendance and track your progress',
    'attendance.quick_checkin': 'Quick Check-in',
    'attendance.scan_qr': 'Scan QR Code',
    'attendance.face_recognition': 'Face Recognition',
    'attendance.ai_powered': 'AI-powered check-in',
    'attendance.attendance_summary': 'Attendance Summary',
    'attendance.overall_rate': 'Overall Attendance Rate',
    'attendance.present': 'Present',
    'attendance.absent': 'Absent',
    'attendance.total': 'Total',
    'attendance.late': 'Late',
    'attendance.status': 'Status',
    'attendance.method': 'Method',
    'attendance.time': 'Time',
    'attendance.date': 'Date',
    'attendance.student': 'Student',
    'attendance.class': 'Class',
    'attendance.records': 'Attendance Records',
    'attendance.history': 'Attendance History',
    
    // Classes
    'classes.title': 'Classes',
    'classes.add_class': 'Add Class',
    'classes.edit_class': 'Edit Class',
    'classes.class_name': 'Class Name',
    'classes.subject': 'Subject',
    'classes.day': 'Day',
    'classes.batch': 'Batch',
    'classes.period': 'Period',
    'classes.teacher_email': 'Teacher Email',
    'classes.room': 'Room',
    'classes.semester': 'Semester',
    'classes.schedule': 'Schedule',
    'classes.students_enrolled': 'Students Enrolled',
    'classes.import_csv': 'Import CSV',
    'classes.export_excel': 'Export Excel',
    
    // Students
    'students.title': 'Students',
    'students.add_student': 'Add Student',
    'students.edit_student': 'Edit Student',
    'students.student_name': 'Student Name',
    'students.student_id': 'Student ID',
    'students.email': 'Email',
    'students.view_profile': 'View Profile',
    'students.attendance_rate': 'Attendance Rate',
    'students.total_attendance': 'Total Attendance',
    'students.enrolled_classes': 'Enrolled Classes',
    
    // Faculty
    'faculty.title': 'Faculty',
    'faculty.add_faculty': 'Add Faculty',
    'faculty.edit_faculty': 'Edit Faculty',
    'faculty.faculty_name': 'Faculty Name',
    'faculty.faculty_id': 'Faculty ID',
    'faculty.department': 'Department',
    'faculty.assigned_classes': 'Assigned Classes',
    
    // Reports
    'reports.title': 'Reports',
    'reports.generate_report': 'Generate Report',
    'reports.report_type': 'Report Type',
    'reports.attendance_records': 'Attendance Records',
    'reports.class_summary': 'Class Summary',
    'reports.student_summary': 'Student Summary',
    'reports.start_date': 'Start Date',
    'reports.end_date': 'End Date',
    'reports.download_pdf': 'Download PDF',
    'reports.download_excel': 'Download Excel',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.overview': 'Overview',
    'analytics.class_trends': 'Class Trends',
    'analytics.student_analysis': 'Student Analysis',
    'analytics.predictions': 'AI Predictions',
    'analytics.patterns': 'Time Patterns',
    'analytics.performance': 'Performance',
    'analytics.top_performers': 'Top Performers',
    'analytics.at_risk_students': 'At Risk Students',
    'analytics.daily_patterns': 'Daily Patterns',
    'analytics.hourly_patterns': 'Hourly Patterns',
    'analytics.attendance_trends': 'Attendance Trends',
    'analytics.class_performance': 'Class Performance',
    'analytics.system_metrics': 'System Metrics',
    'analytics.ai_insights': 'AI Insights',
    'analytics.real_time_reports': 'Real-time Reports',
    'analytics.predictive_analytics': 'Predictive Analytics',
    'analytics.student_insights': 'Student Insights',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.security': 'Security',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.system_config': 'System Config',
    'settings.user_management': 'User Management',
    'settings.class_settings': 'Class Settings',
    'settings.privacy': 'Privacy',
    'settings.full_name': 'Full Name',
    'settings.email_address': 'Email Address',
    'settings.current_password': 'Current Password',
    'settings.new_password': 'New Password',
    'settings.confirm_password': 'Confirm New Password',
    'settings.theme_preferences': 'Theme Preferences',
    'settings.color_theme': 'Color Theme',
    'settings.save_changes': 'Save Changes',
    
    // Auth
    'auth.sign_in': 'Sign In',
    'auth.sign_up': 'Sign Up',
    'auth.sign_out': 'Sign Out',
    'auth.welcome_back': 'Welcome Back',
    'auth.create_account': 'Create your account',
    'auth.email_address': 'Email Address',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.role': 'Role',
    'auth.select_role': 'Select Your Role',
    'auth.remember_me': 'Remember me',
    'auth.forgot_password': 'Forgot your password?',
    'auth.dont_have_account': "Don't have an account?",
    'auth.already_have_account': 'Already have an account?',
    'auth.sign_up_here': 'Sign up here',
    'auth.sign_in_here': 'Sign in here',
    'auth.demo_credentials': 'Demo Credentials',
    'auth.enter_email': 'Enter your email',
    'auth.enter_password': 'Enter your password',
    'auth.signing_in': 'Signing in...',
    'auth.creating_account': 'Creating Account...',
    'auth.back_to_home': 'Back to Home',
    'auth.get_started': 'Get Started',
    'auth.watch_demo': 'Watch Demo',
    'auth.start_free_trial': 'Start Free Trial',
    
    // Landing Page
    'landing.smart_attendance': 'Smart Attendance',
    'landing.made_simple': 'Made Simple',
    'landing.hero_description': 'Experience the future of attendance management with dual-mode technology. QR code scanning and AI-powered face recognition in one elegant platform.',
    'landing.next_generation': 'Next-Generation Attendance Management',
    'landing.powerful_features': 'Powerful Features for Modern Education',
    'landing.features_description': 'Everything you need to manage attendance efficiently with cutting-edge technology and beautiful design',
    'landing.qr_scanning': 'QR Code Scanning',
    'landing.qr_description': 'Instant attendance marking with secure QR codes',
    'landing.face_recognition': 'AI Face Recognition',
    'landing.face_description': 'Advanced facial recognition for seamless check-ins',
    'landing.real_time_analytics': 'Real-time Analytics',
    'landing.analytics_description': 'Live insights and predictive attendance analytics',
    'landing.student_management': 'Student Management',
    'landing.student_description': 'Comprehensive student profiles and attendance tracking',
    'landing.privacy_first': 'Privacy First',
    'landing.privacy_description': 'Secure data handling with privacy controls',
    'landing.real_time_updates': 'Real-time Updates',
    'landing.updates_description': 'Live attendance tracking without page refresh',
    'landing.accuracy_rate': 'Accuracy Rate',
    'landing.ai_powered': 'AI-Powered',
    'landing.face_recognition_stat': 'Face Recognition',
    'landing.secure': 'Secure',
    'landing.data_protection': 'Data Protection',
    'landing.real_time': 'Real-time',
    'landing.live_updates': 'Live Updates',
    'landing.ready_transform': 'Ready to Transform Your Attendance Management?',
    'landing.join_future': 'Join the future of education with our beautiful, powerful attendance system',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.refresh': 'Refresh',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.select': 'Select',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.actions': 'Actions',
    
    // Language names
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.punjabi': 'ਪੰਜਾਬੀ',
    'lang.malayalam': 'മലയാളം',
    
    // Additional common terms
    'common.about': 'About',
    'common.use': 'Use',
    'auth.saved_credentials': 'Saved Credentials',
    'auth.or_continue_with': 'or continue with',
    'auth.admin': 'Admin',
    'auth.faculty': 'Faculty',
    'auth.student': 'Student',
    'landing.about_description': 'Attendify is a comprehensive automated attendance management system designed for modern educational institutions. Our platform combines cutting-edge technology with beautiful design to streamline attendance tracking.'
  },
  
  hi: {
    // Navigation
    'nav.dashboard': 'डैशबोर्ड',
    'nav.attendance': 'उपस्थिति',
    'nav.classes': 'कक्षाएं',
    'nav.students': 'छात्र',
    'nav.faculty': 'संकाय',
    'nav.reports': 'रिपोर्ट',
    'nav.analytics': 'विश्लेषण',
    'nav.settings': 'सेटिंग्स',
    'nav.logout': 'साइन आउट',
    
    // Dashboard
    'dashboard.welcome': 'वापसी पर स्वागत है',
    'dashboard.overall_attendance': 'कुल उपस्थिति',
    'dashboard.total_students': 'कुल छात्र',
    'dashboard.active_classes': 'सक्रिय कक्षाएं',
    'dashboard.at_risk_students': 'जोखिम में छात्र',
    'dashboard.quick_actions': 'त्वरित कार्य',
    'dashboard.start_class': 'कक्षा सत्र शुरू करें',
    'dashboard.face_recognition': 'चेहरा पहचान',
    'dashboard.generate_report': 'रिपोर्ट बनाएं',
    'dashboard.view_analytics': 'विश्लेषण देखें',
    
    // Attendance
    'attendance.title': 'उपस्थिति प्रबंधन',
    'attendance.my_attendance': 'मेरी उपस्थिति',
    'attendance.mark_attendance': 'अपनी उपस्थिति चिह्नित करें और प्रगति ट्रैक करें',
    'attendance.quick_checkin': 'त्वरित चेक-इन',
    'attendance.scan_qr': 'QR कोड स्कैन करें',
    'attendance.face_recognition': 'चेहरा पहचान',
    'attendance.ai_powered': 'AI-संचालित चेक-इन',
    'attendance.attendance_summary': 'उपस्थिति सारांश',
    'attendance.overall_rate': 'कुल उपस्थिति दर',
    'attendance.present': 'उपस्थित',
    'attendance.absent': 'अनुपस्थित',
    'attendance.total': 'कुल',
    'attendance.late': 'देर से',
    'attendance.status': 'स्थिति',
    'attendance.method': 'विधि',
    'attendance.time': 'समय',
    'attendance.date': 'दिनांक',
    'attendance.student': 'छात्र',
    'attendance.class': 'कक्षा',
    'attendance.records': 'उपस्थिति रिकॉर्ड',
    'attendance.history': 'उपस्थिति इतिहास',
    
    // Classes
    'classes.title': 'कक्षाएं',
    'classes.add_class': 'कक्षा जोड़ें',
    'classes.edit_class': 'कक्षा संपादित करें',
    'classes.class_name': 'कक्षा का नाम',
    'classes.subject': 'विषय',
    'classes.day': 'दिन',
    'classes.batch': 'बैच',
    'classes.period': 'अवधि',
    'classes.teacher_email': 'शिक्षक ईमेल',
    'classes.room': 'कमरा',
    'classes.semester': 'सेमेस्टर',
    'classes.schedule': 'समय सारणी',
    'classes.students_enrolled': 'नामांकित छात्र',
    'classes.import_csv': 'CSV आयात करें',
    'classes.export_excel': 'Excel निर्यात करें',
    
    // Students
    'students.title': 'छात्र',
    'students.add_student': 'छात्र जोड़ें',
    'students.edit_student': 'छात्र संपादित करें',
    'students.student_name': 'छात्र का नाम',
    'students.student_id': 'छात्र आईडी',
    'students.email': 'ईमेल',
    'students.view_profile': 'प्रोफ़ाइल देखें',
    'students.attendance_rate': 'उपस्थिति दर',
    'students.total_attendance': 'कुल उपस्थिति',
    'students.enrolled_classes': 'नामांकित कक्षाएं',
    
    // Faculty
    'faculty.title': 'संकाय',
    'faculty.add_faculty': 'संकाय जोड़ें',
    'faculty.edit_faculty': 'संकाय संपादित करें',
    'faculty.faculty_name': 'संकाय का नाम',
    'faculty.faculty_id': 'संकाय आईडी',
    'faculty.department': 'विभाग',
    'faculty.assigned_classes': 'सौंपी गई कक्षाएं',
    
    // Reports
    'reports.title': 'रिपोर्ट',
    'reports.generate_report': 'रिपोर्ट बनाएं',
    'reports.report_type': 'रिपोर्ट प्रकार',
    'reports.attendance_records': 'उपस्थिति रिकॉर्ड',
    'reports.class_summary': 'कक्षा सारांश',
    'reports.student_summary': 'छात्र सारांश',
    'reports.start_date': 'प्रारंभ दिनांक',
    'reports.end_date': 'समाप्ति दिनांक',
    'reports.download_pdf': 'PDF डाउनलोड करें',
    'reports.download_excel': 'Excel डाउनलोड करें',
    
    // Analytics
    'analytics.title': 'विश्लेषण',
    'analytics.overview': 'अवलोकन',
    'analytics.class_trends': 'कक्षा रुझान',
    'analytics.student_analysis': 'छात्र विश्लेषण',
    'analytics.predictions': 'AI भविष्यवाणियां',
    'analytics.patterns': 'समय पैटर्न',
    'analytics.performance': 'प्रदर्शन',
    'analytics.top_performers': 'शीर्ष प्रदर्शनकर्ता',
    'analytics.at_risk_students': 'जोखिम में छात्र',
    'analytics.daily_patterns': 'दैनिक पैटर्न',
    'analytics.hourly_patterns': 'घंटेवार पैटर्न',
    'analytics.attendance_trends': 'उपस्थिति रुझान',
    'analytics.class_performance': 'कक्षा प्रदर्शन',
    'analytics.system_metrics': 'सिस्टम मेट्रिक्स',
    'analytics.ai_insights': 'AI अंतर्दृष्टि',
    'analytics.real_time_reports': 'रीयल-टाइम रिपोर्ट',
    'analytics.predictive_analytics': 'भविष्यसूचक विश्लेषण',
    'analytics.student_insights': 'छात्र अंतर्दृष्टि',
    
    // Settings
    'settings.title': 'सेटिंग्स',
    'settings.profile': 'प्रोफ़ाइल',
    'settings.security': 'सुरक्षा',
    'settings.appearance': 'दिखावट',
    'settings.notifications': 'सूचनाएं',
    'settings.system_config': 'सिस्टम कॉन्फ़िगरेशन',
    'settings.user_management': 'उपयोगकर्ता प्रबंधन',
    'settings.class_settings': 'कक्षा सेटिंग्स',
    'settings.privacy': 'गोपनीयता',
    'settings.full_name': 'पूरा नाम',
    'settings.email_address': 'ईमेल पता',
    'settings.current_password': 'वर्तमान पासवर्ड',
    'settings.new_password': 'नया पासवर्ड',
    'settings.confirm_password': 'नया पासवर्ड पुष्टि करें',
    'settings.theme_preferences': 'थीम प्राथमिकताएं',
    'settings.color_theme': 'रंग थीम',
    'settings.save_changes': 'परिवर्तन सहेजें',
    
    // Auth
    'auth.sign_in': 'साइन इन',
    'auth.sign_up': 'साइन अप',
    'auth.sign_out': 'साइन आउट',
    'auth.welcome_back': 'वापसी पर स्वागत है',
    'auth.create_account': 'अपना खाता बनाएं',
    'auth.email_address': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.confirm_password': 'पासवर्ड की पुष्टि करें',
    'auth.role': 'भूमिका',
    'auth.select_role': 'अपनी भूमिका चुनें',
    'auth.remember_me': 'मुझे याद रखें',
    'auth.forgot_password': 'अपना पासवर्ड भूल गए?',
    'auth.dont_have_account': 'खाता नहीं है?',
    'auth.already_have_account': 'पहले से खाता है?',
    'auth.sign_up_here': 'यहाँ साइन अप करें',
    'auth.sign_in_here': 'यहाँ साइन इन करें',
    'auth.demo_credentials': 'डेमो क्रेडेंशियल',
    'auth.enter_email': 'अपना ईमेल दर्ज करें',
    'auth.enter_password': 'अपना पासवर्ड दर्ज करें',
    'auth.signing_in': 'साइन इन हो रहा है...',
    'auth.creating_account': 'खाता बनाया जा रहा है...',
    'auth.back_to_home': 'होम पर वापस',
    'auth.get_started': 'शुरू करें',
    'auth.watch_demo': 'डेमो देखें',
    'auth.start_free_trial': 'मुफ्त ट्रायल शुरू करें',
    
    // Landing Page
    'landing.smart_attendance': 'स्मार्ट उपस्थिति',
    'landing.made_simple': 'सरल बनाया गया',
    'landing.hero_description': 'दोहरे मोड तकनीक के साथ उपस्थिति प्रबंधन के भविष्य का अनुभव करें। QR कोड स्कैनिंग और AI-संचालित चेहरा पहचान एक सुंदर प्लेटफॉर्म में।',
    'landing.next_generation': 'अगली पीढ़ी का उपस्थिति प्रबंधन',
    'landing.powerful_features': 'आधुनिक शिक्षा के लिए शक्तिशाली सुविधाएं',
    'landing.features_description': 'अत्याधुनिक तकनीक और सुंदर डिज़ाइन के साथ उपस्थिति को कुशलता से प्रबंधित करने के लिए आपको जो कुछ भी चाहिए',
    'landing.qr_scanning': 'QR कोड स्कैनिंग',
    'landing.qr_description': 'सुरक्षित QR कोड के साथ तत्काल उपस्थिति चिह्नित करना',
    'landing.face_recognition': 'AI चेहरा पहचान',
    'landing.face_description': 'निर्बाध चेक-इन के लिए उन्नत चेहरा पहचान',
    'landing.real_time_analytics': 'रीयल-टाइम विश्लेषण',
    'landing.analytics_description': 'लाइव अंतर्दृष्टि और भविष्यसूचक उपस्थिति विश्लेषण',
    'landing.student_management': 'छात्र प्रबंधन',
    'landing.student_description': 'व्यापक छात्र प्रोफाइल और उपस्थिति ट्रैकिंग',
    'landing.privacy_first': 'गोपनीयता पहले',
    'landing.privacy_description': 'गोपनीयता नियंत्रण के साथ सुरक्षित डेटा हैंडलिंग',
    'landing.real_time_updates': 'रीयल-टाइम अपडेट',
    'landing.updates_description': 'पेज रीफ्रेश के बिना लाइव उपस्थिति ट्रैकिंग',
    'landing.accuracy_rate': 'सटीकता दर',
    'landing.ai_powered': 'AI-संचालित',
    'landing.face_recognition_stat': 'चेहरा पहचान',
    'landing.secure': 'सुरक्षित',
    'landing.data_protection': 'डेटा सुरक्षा',
    'landing.real_time': 'रीयल-टाइम',
    'landing.live_updates': 'लाइव अपडेट',
    'landing.ready_transform': 'अपने उपस्थिति प्रबंधन को बदलने के लिए तैयार हैं?',
    'landing.join_future': 'हमारे सुंदर, शक्तिशाली उपस्थिति सिस्टम के साथ शिक्षा के भविष्य में शामिल हों',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.save': 'सेव करें',
    'common.cancel': 'रद्द करें',
    'common.close': 'बंद करें',
    'common.refresh': 'रीफ्रेश',
    'common.export': 'निर्यात',
    'common.import': 'आयात',
    'common.search': 'खोजें',
    'common.filter': 'फिल्टर',
    'common.clear': 'साफ़ करें',
    'common.add': 'जोड़ें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.update': 'अपडेट करें',
    'common.create': 'बनाएं',
    'common.view': 'देखें',
    'common.download': 'डाउनलोड',
    'common.upload': 'अपलोड',
    'common.select': 'चुनें',
    'common.all': 'सभी',
    'common.none': 'कोई नहीं',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'common.success': 'सफलता',
    'common.error': 'त्रुटि',
    'common.warning': 'चेतावनी',
    'common.info': 'जानकारी',
    'common.name': 'नाम',
    'common.email': 'ईमेल',
    'common.date': 'दिनांक',
    'common.time': 'समय',
    'common.status': 'स्थिति',
    'common.actions': 'कार्य',
    
    // Language names
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.punjabi': 'ਪੰਜਾਬੀ',
    'lang.malayalam': 'മലയാളം',
    
    // Additional common terms
    'common.about': 'के बारे में',
    'common.use': 'उपयोग करें',
    'auth.saved_credentials': 'सहेजे गए क्रेडेंशियल',
    'auth.or_continue_with': 'या इसके साथ जारी रखें',
    'auth.admin': 'एडमिन',
    'auth.faculty': 'संकाय',
    'auth.student': 'छात्र',
    'landing.about_description': 'Attendify आधुनिक शैक्षणिक संस्थानों के लिए डिज़ाइन किया गया एक व्यापक स्वचालित उपस्थिति प्रबंधन सिस्टम है। हमारा प्लेटफॉर्म उपस्थिति ट्रैकिंग को सुव्यवस्थित करने के लिए अत्याधुनिक तकनीक को सुंदर डिज़ाइन के साथ जोड़ता है।'
  },
  
  pa: {
    // Navigation
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.attendance': 'ਹਾਜ਼ਰੀ',
    'nav.classes': 'ਕਲਾਸਾਂ',
    'nav.students': 'ਵਿਦਿਆਰਥੀ',
    'nav.faculty': 'ਫੈਕਲਟੀ',
    'nav.reports': 'ਰਿਪੋਰਟਾਂ',
    'nav.analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'nav.settings': 'ਸੈਟਿੰਗਾਂ',
    'nav.logout': 'ਸਾਈਨ ਆਊਟ',
    
    // Dashboard
    'dashboard.welcome': 'ਵਾਪਸੀ ਤੇ ਸੁਆਗਤ ਹੈ',
    'dashboard.overall_attendance': 'ਕੁੱਲ ਹਾਜ਼ਰੀ',
    'dashboard.total_students': 'ਕੁੱਲ ਵਿਦਿਆਰਥੀ',
    'dashboard.active_classes': 'ਸਰਗਰਮ ਕਲਾਸਾਂ',
    'dashboard.at_risk_students': 'ਖਤਰੇ ਵਿੱਚ ਵਿਦਿਆਰਥੀ',
    'dashboard.quick_actions': 'ਤੇਜ਼ ਕਾਰਵਾਈਆਂ',
    'dashboard.start_class': 'ਕਲਾਸ ਸੈਸ਼ਨ ਸ਼ੁਰੂ ਕਰੋ',
    'dashboard.face_recognition': 'ਚਿਹਰਾ ਪਛਾਣ',
    'dashboard.generate_report': 'ਰਿਪੋਰਟ ਬਣਾਓ',
    'dashboard.view_analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ ਦੇਖੋ',
    
    // Attendance
    'attendance.title': 'ਹਾਜ਼ਰੀ ਪ੍ਰਬੰਧਨ',
    'attendance.my_attendance': 'ਮੇਰੀ ਹਾਜ਼ਰੀ',
    'attendance.mark_attendance': 'ਆਪਣੀ ਹਾਜ਼ਰੀ ਨਿਸ਼ਾਨ ਲਗਾਓ ਅਤੇ ਪ੍ਰਗਤੀ ਟਰੈਕ ਕਰੋ',
    'attendance.quick_checkin': 'ਤੇਜ਼ ਚੈੱਕ-ਇਨ',
    'attendance.scan_qr': 'QR ਕੋਡ ਸਕੈਨ ਕਰੋ',
    'attendance.face_recognition': 'ਚਿਹਰਾ ਪਛਾਣ',
    'attendance.ai_powered': 'AI-ਸੰਚਾਲਿਤ ਚੈੱਕ-ਇਨ',
    'attendance.attendance_summary': 'ਹਾਜ਼ਰੀ ਸਾਰਾਂਸ਼',
    'attendance.overall_rate': 'ਕੁੱਲ ਹਾਜ਼ਰੀ ਦਰ',
    'attendance.present': 'ਹਾਜ਼ਰ',
    'attendance.absent': 'ਗੈਰਹਾਜ਼ਰ',
    'attendance.total': 'ਕੁੱਲ',
    'attendance.late': 'ਦੇਰ ਨਾਲ',
    'attendance.status': 'ਸਥਿਤੀ',
    'attendance.method': 'ਤਰੀਕਾ',
    'attendance.time': 'ਸਮਾਂ',
    'attendance.date': 'ਤਾਰੀਖ',
    'attendance.student': 'ਵਿਦਿਆਰਥੀ',
    'attendance.class': 'ਕਲਾਸ',
    'attendance.records': 'ਹਾਜ਼ਰੀ ਰਿਕਾਰਡ',
    'attendance.history': 'ਹਾਜ਼ਰੀ ਇਤਿਹਾਸ',
    
    // Classes
    'classes.title': 'ਕਲਾਸਾਂ',
    'classes.add_class': 'ਕਲਾਸ ਜੋੜੋ',
    'classes.edit_class': 'ਕਲਾਸ ਸੰਪਾਦਿਤ ਕਰੋ',
    'classes.class_name': 'ਕਲਾਸ ਦਾ ਨਾਮ',
    'classes.subject': 'ਵਿਸ਼ਾ',
    'classes.day': 'ਦਿਨ',
    'classes.batch': 'ਬੈਚ',
    'classes.period': 'ਪੀਰੀਅਡ',
    'classes.teacher_email': 'ਅਧਿਆਪਕ ਈਮੇਲ',
    'classes.room': 'ਕਮਰਾ',
    'classes.semester': 'ਸਮੈਸਟਰ',
    'classes.schedule': 'ਸਮਾਂ ਸਾਰਣੀ',
    'classes.students_enrolled': 'ਦਾਖਲ ਵਿਦਿਆਰਥੀ',
    'classes.import_csv': 'CSV ਆਯਾਤ ਕਰੋ',
    'classes.export_excel': 'Excel ਨਿਰਯਾਤ ਕਰੋ',
    
    // Students
    'students.title': 'ਵਿਦਿਆਰਥੀ',
    'students.add_student': 'ਵਿਦਿਆਰਥੀ ਜੋੜੋ',
    'students.edit_student': 'ਵਿਦਿਆਰਥੀ ਸੰਪਾਦਿਤ ਕਰੋ',
    'students.student_name': 'ਵਿਦਿਆਰਥੀ ਦਾ ਨਾਮ',
    'students.student_id': 'ਵਿਦਿਆਰਥੀ ਆਈਡੀ',
    'students.email': 'ਈਮੇਲ',
    'students.view_profile': 'ਪ੍ਰੋਫਾਈਲ ਦੇਖੋ',
    'students.attendance_rate': 'ਹਾਜ਼ਰੀ ਦਰ',
    'students.total_attendance': 'ਕੁੱਲ ਹਾਜ਼ਰੀ',
    'students.enrolled_classes': 'ਦਾਖਲ ਕਲਾਸਾਂ',
    
    // Faculty
    'faculty.title': 'ਫੈਕਲਟੀ',
    'faculty.add_faculty': 'ਫੈਕਲਟੀ ਜੋੜੋ',
    'faculty.edit_faculty': 'ਫੈਕਲਟੀ ਸੰਪਾਦਿਤ ਕਰੋ',
    'faculty.faculty_name': 'ਫੈਕਲਟੀ ਦਾ ਨਾਮ',
    'faculty.faculty_id': 'ਫੈਕਲਟੀ ਆਈਡੀ',
    'faculty.department': 'ਵਿਭਾਗ',
    'faculty.assigned_classes': 'ਸੌਂਪੀਆਂ ਕਲਾਸਾਂ',
    
    // Reports
    'reports.title': 'ਰਿਪੋਰਟਾਂ',
    'reports.generate_report': 'ਰਿਪੋਰਟ ਬਣਾਓ',
    'reports.report_type': 'ਰਿਪੋਰਟ ਕਿਸਮ',
    'reports.attendance_records': 'ਹਾਜ਼ਰੀ ਰਿਕਾਰਡ',
    'reports.class_summary': 'ਕਲਾਸ ਸਾਰਾਂਸ਼',
    'reports.student_summary': 'ਵਿਦਿਆਰਥੀ ਸਾਰਾਂਸ਼',
    'reports.start_date': 'ਸ਼ੁਰੂਆਤੀ ਤਾਰੀਖ',
    'reports.end_date': 'ਅੰਤਿਮ ਤਾਰੀਖ',
    'reports.download_pdf': 'PDF ਡਾਊਨਲੋਡ ਕਰੋ',
    'reports.download_excel': 'Excel ਡਾਊਨਲੋਡ ਕਰੋ',
    
    // Analytics
    'analytics.title': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'analytics.overview': 'ਸੰਖੇਪ',
    'analytics.class_trends': 'ਕਲਾਸ ਰੁਝਾਨ',
    'analytics.student_analysis': 'ਵਿਦਿਆਰਥੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    'analytics.predictions': 'AI ਭਵਿੱਖਬਾਣੀਆਂ',
    'analytics.patterns': 'ਸਮਾਂ ਪੈਟਰਨ',
    'analytics.performance': 'ਪ੍ਰਦਰਸ਼ਨ',
    'analytics.top_performers': 'ਸਿਖਰ ਪ੍ਰਦਰਸ਼ਨਕਾਰ',
    'analytics.at_risk_students': 'ਖਤਰੇ ਵਿੱਚ ਵਿਦਿਆਰਥੀ',
    'analytics.daily_patterns': 'ਰੋਜ਼ਾਨਾ ਪੈਟਰਨ',
    'analytics.hourly_patterns': 'ਘੰਟੇਵਾਰ ਪੈਟਰਨ',
    'analytics.attendance_trends': 'ਹਾਜ਼ਰੀ ਰੁਝਾਨ',
    'analytics.class_performance': 'ਕਲਾਸ ਪ੍ਰਦਰਸ਼ਨ',
    'analytics.system_metrics': 'ਸਿਸਟਮ ਮੈਟ੍ਰਿਕਸ',
    'analytics.ai_insights': 'AI ਸੂਝ',
    'analytics.real_time_reports': 'ਰੀਅਲ-ਟਾਈਮ ਰਿਪੋਰਟਾਂ',
    'analytics.predictive_analytics': 'ਭਵਿੱਖਬਾਣੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    'analytics.student_insights': 'ਵਿਦਿਆਰਥੀ ਸੂਝ',
    
    // Settings
    'settings.title': 'ਸੈਟਿੰਗਾਂ',
    'settings.profile': 'ਪ੍ਰੋਫਾਈਲ',
    'settings.security': 'ਸੁਰੱਖਿਆ',
    'settings.appearance': 'ਦਿੱਖ',
    'settings.notifications': 'ਸੂਚਨਾਵਾਂ',
    'settings.system_config': 'ਸਿਸਟਮ ਕੌਂਫਿਗਰੇਸ਼ਨ',
    'settings.user_management': 'ਯੂਜ਼ਰ ਪ੍ਰਬੰਧਨ',
    'settings.class_settings': 'ਕਲਾਸ ਸੈਟਿੰਗਾਂ',
    'settings.privacy': 'ਗੁਪਤਤਾ',
    'settings.full_name': 'ਪੂਰਾ ਨਾਮ',
    'settings.email_address': 'ਈਮੇਲ ਪਤਾ',
    'settings.current_password': 'ਮੌਜੂਦਾ ਪਾਸਵਰਡ',
    'settings.new_password': 'ਨਵਾਂ ਪਾਸਵਰਡ',
    'settings.confirm_password': 'ਨਵੇਂ ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'settings.theme_preferences': 'ਥੀਮ ਤਰਜੀਹਾਂ',
    'settings.color_theme': 'ਰੰਗ ਥੀਮ',
    'settings.save_changes': 'ਤਬਦੀਲੀਆਂ ਸੇਵ ਕਰੋ',
    
    // Auth
    'auth.sign_in': 'ਸਾਈਨ ਇਨ',
    'auth.sign_up': 'ਸਾਈਨ ਅੱਪ',
    'auth.sign_out': 'ਸਾਈਨ ਆਊਟ',
    'auth.welcome_back': 'ਵਾਪਸੀ ਤੇ ਸੁਆਗਤ ਹੈ',
    'auth.create_account': 'ਆਪਣਾ ਖਾਤਾ ਬਣਾਓ',
    'auth.email_address': 'ਈਮੇਲ ਪਤਾ',
    'auth.password': 'ਪਾਸਵਰਡ',
    'auth.confirm_password': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'auth.role': 'ਭੂਮਿਕਾ',
    'auth.select_role': 'ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ',
    'auth.remember_me': 'ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ',
    'auth.forgot_password': 'ਆਪਣਾ ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    'auth.dont_have_account': 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    'auth.already_have_account': 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
    'auth.sign_up_here': 'ਇੱਥੇ ਸਾਈਨ ਅੱਪ ਕਰੋ',
    'auth.sign_in_here': 'ਇੱਥੇ ਸਾਈਨ ਇਨ ਕਰੋ',
    'auth.demo_credentials': 'ਡੈਮੋ ਕ੍ਰੇਡੈਂਸ਼ੀਅਲ',
    'auth.enter_email': 'ਆਪਣਾ ਈਮੇਲ ਦਰਜ ਕਰੋ',
    'auth.enter_password': 'ਆਪਣਾ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',
    'auth.signing_in': 'ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...',
    'auth.creating_account': 'ਖਾਤਾ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...',
    'auth.back_to_home': 'ਘਰ ਵਾਪਸ',
    'auth.get_started': 'ਸ਼ੁਰੂ ਕਰੋ',
    'auth.watch_demo': 'ਡੈਮੋ ਦੇਖੋ',
    'auth.start_free_trial': 'ਮੁਫਤ ਟ੍ਰਾਇਲ ਸ਼ੁਰੂ ਕਰੋ',
    
    // Landing Page
    'landing.smart_attendance': 'ਸਮਾਰਟ ਹਾਜ਼ਰੀ',
    'landing.made_simple': 'ਸਰਲ ਬਣਾਇਆ ਗਿਆ',
    'landing.hero_description': 'ਦੋਹਰੇ ਮੋਡ ਤਕਨਾਲੋਜੀ ਨਾਲ ਹਾਜ਼ਰੀ ਪ੍ਰਬੰਧਨ ਦੇ ਭਵਿੱਖ ਦਾ ਅਨੁਭਵ ਕਰੋ। QR ਕੋਡ ਸਕੈਨਿੰਗ ਅਤੇ AI-ਸੰਚਾਲਿਤ ਚਿਹਰਾ ਪਛਾਣ ਇੱਕ ਸੁੰਦਰ ਪਲੇਟਫਾਰਮ ਵਿੱਚ।',
    'landing.next_generation': 'ਅਗਲੀ ਪੀੜ੍ਹੀ ਦਾ ਹਾਜ਼ਰੀ ਪ੍ਰਬੰਧਨ',
    'landing.powerful_features': 'ਆਧੁਨਿਕ ਸਿੱਖਿਆ ਲਈ ਸ਼ਕਤੀਸ਼ਾਲੀ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    'landing.features_description': 'ਅਤਿ-ਆਧੁਨਿਕ ਤਕਨਾਲੋਜੀ ਅਤੇ ਸੁੰਦਰ ਡਿਜ਼ਾਈਨ ਨਾਲ ਹਾਜ਼ਰੀ ਨੂੰ ਕੁਸ਼ਲਤਾ ਨਾਲ ਪ੍ਰਬੰਧਿਤ ਕਰਨ ਲਈ ਤੁਹਾਨੂੰ ਜੋ ਕੁਝ ਚਾਹੀਦਾ ਹੈ',
    'landing.qr_scanning': 'QR ਕੋਡ ਸਕੈਨਿੰਗ',
    'landing.qr_description': 'ਸੁਰੱਖਿਤ QR ਕੋਡ ਨਾਲ ਤੁਰੰਤ ਹਾਜ਼ਰੀ ਨਿਸ਼ਾਨ ਲਗਾਉਣਾ',
    'landing.face_recognition': 'AI ਚਿਹਰਾ ਪਛਾਣ',
    'landing.face_description': 'ਨਿਰਵਿਘਨ ਚੈੱਕ-ਇਨ ਲਈ ਉੱਨਤ ਚਿਹਰਾ ਪਛਾਣ',
    'landing.real_time_analytics': 'ਰੀਅਲ-ਟਾਈਮ ਵਿਸ਼ਲੇਸ਼ਣ',
    'landing.analytics_description': 'ਲਾਈਵ ਸੂਝ ਅਤੇ ਭਵਿੱਖਬਾਣੀ ਹਾਜ਼ਰੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    'landing.student_management': 'ਵਿਦਿਆਰਥੀ ਪ੍ਰਬੰਧਨ',
    'landing.student_description': 'ਵਿਆਪਕ ਵਿਦਿਆਰਥੀ ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਹਾਜ਼ਰੀ ਟਰੈਕਿੰਗ',
    'landing.privacy_first': 'ਗੁਪਤਤਾ ਪਹਿਲਾਂ',
    'landing.privacy_description': 'ਗੁਪਤਤਾ ਨਿਯੰਤਰਣ ਨਾਲ ਸੁਰੱਖਿਤ ਡੇਟਾ ਹੈਂਡਲਿੰਗ',
    'landing.real_time_updates': 'ਰੀਅਲ-ਟਾਈਮ ਅੱਪਡੇਟ',
    'landing.updates_description': 'ਪੇਜ ਰੀਫ੍ਰੈਸ਼ ਤੋਂ ਬਿਨਾਂ ਲਾਈਵ ਹਾਜ਼ਰੀ ਟਰੈਕਿੰਗ',
    'landing.accuracy_rate': 'ਸਟੀਕਤਾ ਦਰ',
    'landing.ai_powered': 'AI-ਸੰਚਾਲਿਤ',
    'landing.face_recognition_stat': 'ਚਿਹਰਾ ਪਛਾਣ',
    'landing.secure': 'ਸੁਰੱਖਿਤ',
    'landing.data_protection': 'ਡੇਟਾ ਸੁਰੱਖਿਆ',
    'landing.real_time': 'ਰੀਅਲ-ਟਾਈਮ',
    'landing.live_updates': 'ਲਾਈਵ ਅੱਪਡੇਟ',
    'landing.ready_transform': 'ਆਪਣੇ ਹਾਜ਼ਰੀ ਪ੍ਰਬੰਧਨ ਨੂੰ ਬਦਲਣ ਲਈ ਤਿਆਰ ਹੋ?',
    'landing.join_future': 'ਸਾਡੇ ਸੁੰਦਰ, ਸ਼ਕਤੀਸ਼ਾਲੀ ਹਾਜ਼ਰੀ ਸਿਸਟਮ ਨਾਲ ਸਿੱਖਿਆ ਦੇ ਭਵਿੱਖ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    
    // Common
    'common.loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'common.save': 'ਸੇਵ ਕਰੋ',
    'common.cancel': 'ਰੱਦ ਕਰੋ',
    'common.close': 'ਬੰਦ ਕਰੋ',
    'common.refresh': 'ਰੀਫ੍ਰੈਸ਼',
    'common.export': 'ਨਿਰਯਾਤ',
    'common.import': 'ਆਯਾਤ',
    'common.search': 'ਖੋਜੋ',
    'common.filter': 'ਫਿਲਟਰ',
    'common.clear': 'ਸਾਫ਼ ਕਰੋ',
    'common.add': 'ਜੋੜੋ',
    'common.edit': 'ਸੰਪਾਦਿਤ ਕਰੋ',
    'common.delete': 'ਮਿਟਾਓ',
    'common.update': 'ਅੱਪਡੇਟ ਕਰੋ',
    'common.create': 'ਬਣਾਓ',
    'common.view': 'ਦੇਖੋ',
    'common.download': 'ਡਾਊਨਲੋਡ',
    'common.upload': 'ਅੱਪਲੋਡ',
    'common.select': 'ਚੁਣੋ',
    'common.all': 'ਸਭ',
    'common.none': 'ਕੋਈ ਨਹੀਂ',
    'common.yes': 'ਹਾਂ',
    'common.no': 'ਨਹੀਂ',
    'common.success': 'ਸਫਲਤਾ',
    'common.error': 'ਗਲਤੀ',
    'common.warning': 'ਚੇਤਾਵਨੀ',
    'common.info': 'ਜਾਣਕਾਰੀ',
    'common.name': 'ਨਾਮ',
    'common.email': 'ਈਮੇਲ',
    'common.date': 'ਤਾਰੀਖ',
    'common.time': 'ਸਮਾਂ',
    'common.status': 'ਸਥਿਤੀ',
    'common.actions': 'ਕਾਰਵਾਈਆਂ',
    
    // Language names
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.punjabi': 'ਪੰਜਾਬੀ',
    'lang.malayalam': 'മലയാളം',
    
    // Additional common terms
    'common.about': 'ਬਾਰੇ',
    'common.use': 'ਵਰਤੋ',
    'auth.saved_credentials': 'ਸੇਵ ਕੀਤੇ ਕ੍ਰੇਡੈਂਸ਼ੀਅਲ',
    'auth.or_continue_with': 'ਜਾਂ ਇਸ ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    'auth.admin': 'ਐਡਮਿਨ',
    'auth.faculty': 'ਫੈਕਲਟੀ',
    'auth.student': 'ਵਿਦਿਆਰਥੀ',
    'landing.about_description': 'Attendify ਆਧੁਨਿਕ ਸਿੱਖਿਆ ਸੰਸਥਾਵਾਂ ਲਈ ਡਿਜ਼ਾਈਨ ਕੀਤਾ ਗਿਆ ਇੱਕ ਵਿਆਪਕ ਸਵੈਚਲਿਤ ਹਾਜ਼ਰੀ ਪ੍ਰਬੰਧਨ ਸਿਸਟਮ ਹੈ। ਸਾਡਾ ਪਲੇਟਫਾਰਮ ਹਾਜ਼ਰੀ ਟਰੈਕਿੰਗ ਨੂੰ ਸੁਚਾਰੂ ਬਣਾਉਣ ਲਈ ਅਤਿ-ਆਧੁਨਿਕ ਤਕਨਾਲੋਜੀ ਨੂੰ ਸੁੰਦਰ ਡਿਜ਼ਾਈਨ ਨਾਲ ਜੋੜਦਾ ਹੈ।'
  },
  
  ml: {
    // Navigation
    'nav.dashboard': 'ഡാഷ്‌ബോർഡ്',
    'nav.attendance': 'ഹാജർ',
    'nav.classes': 'ക്ലാസുകൾ',
    'nav.students': 'വിദ്യാർത്ഥികൾ',
    'nav.faculty': 'ഫാക്കൽറ്റി',
    'nav.reports': 'റിപ്പോർട്ടുകൾ',
    'nav.analytics': 'വിശകലനം',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'nav.logout': 'സൈൻ ഔട്ട്',
    'nav.features': 'സവിശേഷതകൾ',
    
    // Dashboard
    'dashboard.welcome': 'തിരിച്ചുവരവിൽ സ്വാഗതം',
    'dashboard.overall_attendance': 'മൊത്തം ഹാജർ',
    'dashboard.total_students': 'മൊത്തം വിദ്യാർത്ഥികൾ',
    'dashboard.active_classes': 'സജീവ ക്ലാസുകൾ',
    'dashboard.at_risk_students': 'അപകടത്തിലുള്ള വിദ്യാർത്ഥികൾ',
    'dashboard.quick_actions': 'വേഗത്തിലുള്ള പ്രവർത്തനങ്ങൾ',
    'dashboard.start_class': 'ക്ലാസ് സെഷൻ ആരംഭിക്കുക',
    'dashboard.face_recognition': 'മുഖം തിരിച്ചറിയൽ',
    'dashboard.generate_report': 'റിപ്പോർട്ട് സൃഷ്ടിക്കുക',
    'dashboard.view_analytics': 'വിശകലനം കാണുക',
    
    // Attendance
    'attendance.title': 'ഹാജർ മാനേജ്മെന്റ്',
    'attendance.my_attendance': 'എന്റെ ഹാജർ',
    'attendance.mark_attendance': 'നിങ്ങളുടെ ഹാജർ അടയാളപ്പെടുത്തുകയും പുരോഗതി ട്രാക്ക് ചെയ്യുകയും ചെയ്യുക',
    'attendance.quick_checkin': 'വേഗത്തിലുള്ള ചെക്ക്-ഇൻ',
    'attendance.scan_qr': 'QR കോഡ് സ്കാൻ ചെയ്യുക',
    'attendance.face_recognition': 'മുഖം തിരിച്ചറിയൽ',
    'attendance.ai_powered': 'AI-പവർഡ് ചെക്ക്-ഇൻ',
    'attendance.attendance_summary': 'ഹാജർ സംഗ്രഹം',
    'attendance.overall_rate': 'മൊത്തം ഹാജർ നിരക്ക്',
    'attendance.present': 'ഹാജർ',
    'attendance.absent': 'ഹാജരല്ലാത്ത',
    'attendance.total': 'മൊത്തം',
    'attendance.late': 'വൈകി',
    'attendance.status': 'നില',
    'attendance.method': 'രീതി',
    'attendance.time': 'സമയം',
    'attendance.date': 'തീയതി',
    'attendance.student': 'വിദ്യാർത്ഥി',
    'attendance.class': 'ക്ലാസ്',
    'attendance.records': 'ഹാജർ റെക്കോർഡുകൾ',
    'attendance.history': 'ഹാജർ ചരിത്രം',
    
    // Classes
    'classes.title': 'ക്ലാസുകൾ',
    'classes.add_class': 'ക്ലാസ് ചേർക്കുക',
    'classes.edit_class': 'ക്ലാസ് എഡിറ്റ് ചെയ്യുക',
    'classes.class_name': 'ക്ലാസിന്റെ പേര്',
    'classes.subject': 'വിഷയം',
    'classes.day': 'ദിവസം',
    'classes.batch': 'ബാച്ച്',
    'classes.period': 'പിരീഡ്',
    'classes.teacher_email': 'അധ്യാപക ഇമെയിൽ',
    'classes.room': 'മുറി',
    'classes.semester': 'സെമസ്റ്റർ',
    'classes.schedule': 'ഷെഡ്യൂൾ',
    'classes.students_enrolled': 'എൻറോൾ ചെയ്ത വിദ്യാർത്ഥികൾ',
    'classes.import_csv': 'CSV ഇമ്പോർട്ട് ചെയ്യുക',
    'classes.export_excel': 'Excel എക്സ്പോർട്ട് ചെയ്യുക',
    
    // Students
    'students.title': 'വിദ്യാർത്ഥികൾ',
    'students.add_student': 'വിദ്യാർത്ഥി ചേർക്കുക',
    'students.edit_student': 'വിദ്യാർത്ഥി എഡിറ്റ് ചെയ്യുക',
    'students.student_name': 'വിദ്യാർത്ഥിയുടെ പേര്',
    'students.student_id': 'വിദ്യാർത്ഥി ഐഡി',
    'students.email': 'ഇമെയിൽ',
    'students.view_profile': 'പ്രൊഫൈൽ കാണുക',
    'students.attendance_rate': 'ഹാജർ നിരക്ക്',
    'students.total_attendance': 'മൊത്തം ഹാജർ',
    'students.enrolled_classes': 'എൻറോൾ ചെയ്ത ക്ലാസുകൾ',
    
    // Faculty
    'faculty.title': 'ഫാക്കൽറ്റി',
    'faculty.add_faculty': 'ഫാക്കൽറ്റി ചേർക്കുക',
    'faculty.edit_faculty': 'ഫാക്കൽറ്റി എഡിറ്റ് ചെയ്യുക',
    'faculty.faculty_name': 'ഫാക്കൽറ്റിയുടെ പേര്',
    'faculty.faculty_id': 'ഫാക്കൽറ്റി ഐഡി',
    'faculty.department': 'വകുപ്പ്',
    'faculty.assigned_classes': 'നിയുക്ത ക്ലാസുകൾ',
    
    // Reports
    'reports.title': 'റിപ്പോർട്ടുകൾ',
    'reports.generate_report': 'റിപ്പോർട്ട് സൃഷ്ടിക്കുക',
    'reports.report_type': 'റിപ്പോർട്ട് തരം',
    'reports.attendance_records': 'ഹാജർ റെക്കോർഡുകൾ',
    'reports.class_summary': 'ക്ലാസ് സംഗ്രഹം',
    'reports.student_summary': 'വിദ്യാർത്ഥി സംഗ്രഹം',
    'reports.start_date': 'ആരംഭ തീയതി',
    'reports.end_date': 'അവസാന തീയതി',
    'reports.download_pdf': 'PDF ഡൗൺലോഡ് ചെയ്യുക',
    'reports.download_excel': 'Excel ഡൗൺലോഡ് ചെയ്യുക',
    
    // Analytics
    'analytics.title': 'വിശകലനം',
    'analytics.overview': 'അവലോകനം',
    'analytics.class_trends': 'ക്ലാസ് ട്രെൻഡുകൾ',
    'analytics.student_analysis': 'വിദ്യാർത്ഥി വിശകലനം',
    'analytics.predictions': 'AI പ്രവചനങ്ങൾ',
    'analytics.patterns': 'സമയ പാറ്റേണുകൾ',
    'analytics.performance': 'പ്രകടനം',
    'analytics.top_performers': 'മികച്ച പ്രകടനം കാഴ്ചവെക്കുന്നവർ',
    'analytics.at_risk_students': 'അപകടത്തിലുള്ള വിദ്യാർത്ഥികൾ',
    'analytics.daily_patterns': 'ദൈനംദിന പാറ്റേണുകൾ',
    'analytics.hourly_patterns': 'മണിക്കൂർ പാറ്റേണുകൾ',
    'analytics.attendance_trends': 'ഹാജർ ട്രെൻഡുകൾ',
    'analytics.class_performance': 'ക്ലാസ് പ്രകടനം',
    'analytics.system_metrics': 'സിസ്റ്റം മെട്രിക്സ്',
    'analytics.ai_insights': 'AI ഉൾക്കാഴ്ചകൾ',
    'analytics.real_time_reports': 'റിയൽ-ടൈം റിപ്പോർട്ടുകൾ',
    'analytics.predictive_analytics': 'പ്രവചന വിശകലനം',
    'analytics.student_insights': 'വിദ്യാർത്ഥി ഉൾക്കാഴ്ചകൾ',
    
    // Settings
    'settings.title': 'ക്രമീകരണങ്ങൾ',
    'settings.profile': 'പ്രൊഫൈൽ',
    'settings.security': 'സുരക്ഷ',
    'settings.appearance': 'രൂപം',
    'settings.notifications': 'അറിയിപ്പുകൾ',
    'settings.system_config': 'സിസ്റ്റം കോൺഫിഗറേഷൻ',
    'settings.user_management': 'ഉപയോക്തൃ മാനേജ്മെന്റ്',
    'settings.class_settings': 'ക്ലാസ് ക്രമീകരണങ്ങൾ',
    'settings.privacy': 'സ്വകാര്യത',
    'settings.full_name': 'പൂർണ്ണ നാമം',
    'settings.email_address': 'ഇമെയിൽ വിലാസം',
    'settings.current_password': 'നിലവിലെ പാസ്‌വേഡ്',
    'settings.new_password': 'പുതിയ പാസ്‌വേഡ്',
    'settings.confirm_password': 'പുതിയ പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'settings.theme_preferences': 'തീം മുൻഗണനകൾ',
    'settings.color_theme': 'വർണ്ണ തീം',
    'settings.save_changes': 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
    
    // Auth
    'auth.sign_in': 'സൈൻ ഇൻ',
    'auth.sign_up': 'സൈൻ അപ്പ്',
    'auth.sign_out': 'സൈൻ ഔട്ട്',
    'auth.welcome_back': 'തിരിച്ചുവരവിൽ സ്വാഗതം',
    'auth.create_account': 'നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'auth.email_address': 'ഇമെയിൽ വിലാസം',
    'auth.password': 'പാസ്‌വേഡ്',
    'auth.confirm_password': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'auth.role': 'റോൾ',
    'auth.select_role': 'നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക',
    'auth.remember_me': 'എന്നെ ഓർക്കുക',
    'auth.forgot_password': 'നിങ്ങളുടെ പാസ്‌വേഡ് മറന്നോ?',
    'auth.dont_have_account': 'അക്കൗണ്ട് ഇല്ലേ?',
    'auth.already_have_account': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    'auth.sign_up_here': 'ഇവിടെ സൈൻ അപ്പ് ചെയ്യുക',
    'auth.sign_in_here': 'ഇവിടെ സൈൻ ഇൻ ചെയ്യുക',
    'auth.demo_credentials': 'ഡെമോ ക്രെഡൻഷ്യലുകൾ',
    'auth.enter_email': 'നിങ്ങളുടെ ഇമെയിൽ നൽകുക',
    'auth.enter_password': 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
    'auth.signing_in': 'സൈൻ ഇൻ ചെയ്യുന്നു...',
    'auth.creating_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു...',
    'auth.back_to_home': 'ഹോമിലേക്ക് മടങ്ങുക',
    'auth.get_started': 'ആരംഭിക്കുക',
    'auth.watch_demo': 'ഡെമോ കാണുക',
    'auth.start_free_trial': 'സൗജന്യ ട്രയൽ ആരംഭിക്കുക',
    
    // Landing Page
    'landing.smart_attendance': 'സ്മാർട്ട് ഹാജർ',
    'landing.made_simple': 'ലളിതമാക്കി',
    'landing.hero_description': 'ഇരട്ട മോഡ് സാങ്കേതികവിദ്യയുമായി ഹാജർ മാനേജ്മെന്റിന്റെ ഭാവി അനുഭവിക്കുക. QR കോഡ് സ്കാനിംഗും AI-പവർഡ് ഫേസ് റെക്കഗ്നിഷനും ഒരു മനോഹരമായ പ്ലാറ്റ്ഫോമിൽ.',
    'landing.next_generation': 'അടുത്ത തലമുറ ഹാജർ മാനേജ്മെന്റ്',
    'landing.powerful_features': 'ആധുനിക വിദ്യാഭ്യാസത്തിനുള്ള ശക്തമായ സവിശേഷതകൾ',
    'landing.features_description': 'അത്യാധുനിക സാങ്കേതികവിദ്യയും മനോഹരമായ ഡിസൈനും ഉപയോഗിച്ച് ഹാജർ കാര്യക്ഷമമായി കൈകാര്യം ചെയ്യാൻ നിങ്ങൾക്ക് ആവശ്യമായതെല്ലാം',
    'landing.qr_scanning': 'QR കോഡ് സ്കാനിംഗ്',
    'landing.qr_description': 'സുരക്ഷിത QR കോഡുകൾ ഉപയോഗിച്ച് തൽക്ഷണ ഹാജർ അടയാളപ്പെടുത്തൽ',
    'landing.face_recognition': 'AI ഫേസ് റെക്കഗ്നിഷൻ',
    'landing.face_description': 'തടസ്സമില്ലാത്ത ചെക്ക്-ഇനുകൾക്കായി വിപുലമായ ഫേഷ്യൽ റെക്കഗ്നിഷൻ',
    'landing.real_time_analytics': 'റിയൽ-ടൈം അനലിറ്റിക്സ്',
    'landing.analytics_description': 'തത്സമയ ഉൾക്കാഴ്ചകളും പ്രവചന ഹാജർ വിശകലനവും',
    'landing.student_management': 'വിദ്യാർത്ഥി മാനേജ്മെന്റ്',
    'landing.student_description': 'സമഗ്രമായ വിദ്യാർത്ഥി പ്രൊഫൈലുകളും ഹാജർ ട്രാക്കിംഗും',
    'landing.privacy_first': 'സ്വകാര്യത ആദ്യം',
    'landing.privacy_description': 'സ്വകാര്യത നിയന്ത്രണങ്ങളോടെ സുരക്ഷിത ഡാറ്റ കൈകാര്യം',
    'landing.real_time_updates': 'റിയൽ-ടൈം അപ്ഡേറ്റുകൾ',
    'landing.updates_description': 'പേജ് റിഫ്രഷ് ഇല്ലാതെ തത്സമയ ഹാജർ ട്രാക്കിംഗ്',
    'landing.accuracy_rate': 'കൃത്യത നിരക്ക്',
    'landing.ai_powered': 'AI-പവർഡ്',
    'landing.face_recognition_stat': 'ഫേസ് റെക്കഗ്നിഷൻ',
    'landing.secure': 'സുരക്ഷിത',
    'landing.data_protection': 'ഡാറ്റ സംരക്ഷണം',
    'landing.real_time': 'റിയൽ-ടൈം',
    'landing.live_updates': 'തത്സമയ അപ്ഡേറ്റുകൾ',
    'landing.ready_transform': 'നിങ്ങളുടെ ഹാജർ മാനേജ്മെന്റ് പരിവർത്തനം ചെയ്യാൻ തയ്യാറാണോ?',
    'landing.join_future': 'ഞങ്ങളുടെ മനോഹരവും ശക്തവുമായ ഹാജർ സിസ്റ്റം ഉപയോഗിച്ച് വിദ്യാഭ്യാസത്തിന്റെ ഭാവിയിൽ ചേരുക',
    
    // Common
    'common.loading': 'ലോഡ് ചെയ്യുന്നു...',
    'common.save': 'സേവ് ചെയ്യുക',
    'common.cancel': 'റദ്ദാക്കുക',
    'common.close': 'അടയ്ക്കുക',
    'common.refresh': 'പുതുക്കുക',
    'common.export': 'കയറ്റുമതി',
    'common.import': 'ഇറക്കുമതി',
    'common.search': 'തിരയുക',
    'common.filter': 'ഫിൽട്ടർ',
    'common.clear': 'മായ്ക്കുക',
    'common.add': 'ചേർക്കുക',
    'common.edit': 'എഡിറ്റ് ചെയ്യുക',
    'common.delete': 'ഇല്ലാതാക്കുക',
    'common.update': 'അപ്ഡേറ്റ് ചെയ്യുക',
    'common.create': 'സൃഷ്ടിക്കുക',
    'common.view': 'കാണുക',
    'common.download': 'ഡൗൺലോഡ്',
    'common.upload': 'അപ്‌ലോഡ്',
    'common.select': 'തിരഞ്ഞെടുക്കുക',
    'common.all': 'എല്ലാം',
    'common.none': 'ഒന്നുമില്ല',
    'common.yes': 'അതെ',
    'common.no': 'ഇല്ല',
    'common.success': 'വിജയം',
    'common.error': 'പിശക്',
    'common.warning': 'മുന്നറിയിപ്പ്',
    'common.info': 'വിവരം',
    'common.name': 'പേര്',
    'common.email': 'ഇമെയിൽ',
    'common.date': 'തീയതി',
    'common.time': 'സമയം',
    'common.status': 'നില',
    'common.actions': 'പ്രവർത്തനങ്ങൾ',
    
    // Language names
    'lang.english': 'English',
    'lang.hindi': 'हिंदी',
    'lang.punjabi': 'ਪੰਜਾਬੀ',
    'lang.malayalam': 'മലയാളം',
    
    // Additional common terms
    'common.about': 'കുറിച്ച്',
    'common.use': 'ഉപയോഗിക്കുക',
    'auth.saved_credentials': 'സേവ് ചെയ്ത ക്രെഡൻഷ്യലുകൾ',
    'auth.or_continue_with': 'അല്ലെങ്കിൽ ഇതുമായി തുടരുക',
    'auth.admin': 'അഡ്മിൻ',
    'auth.faculty': 'ഫാക്കൽറ്റി',
    'auth.student': 'വിദ്യാർത്ഥി',
    'landing.about_description': 'Attendify ആധുനിക വിദ്യാഭ്യാസ സ്ഥാപനങ്ങൾക്കായി രൂപകൽപ്പന ചെയ്ത ഒരു സമഗ്ര ഓട്ടോമേറ്റഡ് ഹാജർ മാനേജ്മെന്റ് സിസ്റ്റമാണ്. ഞങ്ങളുടെ പ്ലാറ്റ്ഫോം ഹാജർ ട്രാക്കിംഗ് കാര്യക്ഷമമാക്കാൻ അത്യാധുനിക സാങ്കേതികവിദ്യയെ മനോഹരമായ ഡിസൈനുമായി സംയോജിപ്പിക്കുന്നു।'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('attendify_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('attendify_language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key as keyof typeof translations.en] || key;
  };

  useEffect(() => {
    // Set document language attribute
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};